### ISSUE TITLE
Feature request: more gamers

### ISSUE THREAD

**Issue by arnemolland** [artinbeyati/Portfolio#2]
I want to see more gamers, not just one. We need representation.

They targeted gamers.

Gamers.

We're a group of people who will sit for hours, days, even weeks on end performing some of the hardest, most mentally demanding tasks. Over, and over, and over all for nothing more than a little digital token saying we did.

We'll punish our selfs doing things others would consider torture, because we think it's fun.

We'll spend most if not all of our free time min maxing the stats of a fictional character all to draw out a single extra point of damage per second.

Many of us have made careers out of doing just these things: slogging through the grind, all day, the same quests over and over, hundreds of times to the point where we know evety little detail such that some have attained such gamer nirvana that they can literally play these games blindfolded.

Do these people have any idea how many controllers have been smashed, systems over heated, disks and carts destroyed 8n frustration? All to latter be referred to as bragging rights?

These people honestly think this is a battle they can win? They take our media? We're already building a new one without them. They take our devs? Gamers aren't shy about throwing their money else where, or even making the games our selves. They think calling us racist, mysoginistic, rape apologists is going to change us? We've been called worse things by prepubescent 10 year olds with a shitty head set. They picked a fight against a group that's already grown desensitized to their strategies and methods. Who enjoy the battle of attrition they've threatened us with. Who take it as a challange when they tell us we no longer matter. Our obsession with proving we can after being told we can't is so deeply ingrained from years of dealing with big brothers/sisters and friends laughing at how pathetic we used to be that proving you people wrong has become a very real need; a honed reflex.

Gamers are competative, hard core, by nature. We love a challange. The worst thing you did in all of this was to challange us. You're not special, you're not original, you're not the first; this is just another boss fight.

**Comment by artinbeyati** [comment]
Very cool, thanks 👍

**Comment by sondregj** [comment]
+1
